all:
  vars:
    ansible_user: ansible
    build_number: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    required_docker_label: "org.homelab.application=conjur"
    CONJUR_PASSWORD: "{{ lookup('env', 'CONJUR_PASSWORD') }}"
  hosts:
    # cdeed53d37a742f08a227faafc832595:
    #   ansible_host: 192.168.0.20
    # 9c9b38653dae4f4ebbd120adba40ac33:
    #   ansible_host: 192.168.0.28
    ad42e8b2fa7d4a3dbc5aecef7810a624:
      ansible_host: 192.168.0.21
      docker_networks:
        - name: conjur
          driver: bridge
      docker_volumes: []
      docker_containers:
        - name: conjur_cli_configure
          image: ghcr.io/andrewjdawes/home-lab-conjur-cli-configure:v2
          pull: true
          state: started
          restart: true
          auto_remove: false
          restart_policy: "on-failure"
          restart_retries: 150
          env:
            CONJUR_SERVER_APPLIANCE_URL: http://conjur:80
            CONJUR_ORG_ACCOUNT: codekaizen
            CONJUR_USERNAME: admin
            CONJUR_PASSWORD: "{{ CONJUR_PASSWORD }}"
            CONJUR_CLI_INSECURE: "true"
            CONJUR_AUTHN_JWT_JENKINS_ISSUER: https://jenkins.codekaizen.net
            CONJUR_AUTHN_JWT_JENKINS_JWKS_URI: https://jenkins-conjur-jwk.codekaizen.net/jwtauth/conjur-jwk-set
            CONJUR_AUTHN_JWT_JENKINS_AUDIENCE: cyberark-conjur
          networks:
            - name: conjur
          labels:
            org.homelab.application: conjur
            org.homelab.service: cli-configure
            # org.codekaizen.build_number: "{{ build_number }}" # will force a recreate
          comparisons:
            image: strict # restart if the image has changed
            env: strict # we want precisely this environment
            volumes: allow_more_present # if there are more volumes, that's ok, as long as `/tmp:/tmp` is there
            networks: strict # if there are more networks, that's ok, as long as `mynet` is there
          replica_count: 1
          filters_string: '--filter "label=org.homelab.application=conjur" --filter "label=org.homelab.service=cli-configure"'
          deploy_strategy: "recreate"
